name: whatsapp_stickers_example
description: Demonstrates how to use the whatsapp_stickers plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_whatsapp_stickers:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - sticker_packs/1/
    - sticker_packs/2/
    - sticker_packs/sticker_packs.json
