name: flutter_whatsapp_stickers
description: Flutter plugin for adding WhatsApp Stickers within your flutter app.
version: 1.0.0+4
homepage: https://github.com/vincekruger/flutter_whatsapp_stickers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^2.2.1
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.vincekruger.whatsapp_stickers
        pluginClass: WhatsAppStickersPlugin