name: flutter_whatsapp_stickers
description: A flutter plugin for Whatsapp stickers.
version: 0.0.1
author: Vince <vincekruger@gmail.com>
homepage: https://github.com/vincekruger/flutter_whatsapp_stickers

flutter:
  plugin:
    androidPackage: io.github.vincekruger.whatsapp_stickers
    pluginClass: WhatsAppStickersPlugin

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.2.2 <3.0.0"