name: whatsapp_stickers_example_dynamic
description: Demonstrates how to use the whatsapp_stickers plugin with dynamic content.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_whatsapp_stickers:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - sticker_packs/cats.zip
    - sticker_packs/dragon.zip
